params ["_unit","_ms","_time"];
_unit action ["DropWeapon", ("GroundWeaponHolder_Scripted" createVehicle position _unit), currentWeapon _unit];
sleep _time;
[_unit, true] call ace_captives_fnc_setSurrendered;
waituntil {sleep _time; _ms countSide nearestObjects [getpos _unit, ["AllVehicles"], (getpos (_unit findNearestEnemy getpos _unit)) distance (getpos _unit)] > 1;};
[_unit, false] call ace_captives_fnc_setSurrendered;
sleep _time;
private _wh = nearestObjects [_unit, ["WeaponHolder", "WeaponHolderSimulated"], 50];
private _containers = [];
{if (count (weaponcargo _x) > 0) then {_containers pushback _x};} forEach _wh;
if (count _containers > 0) then {_unit action ["TakeWeapon", (_containers select 0), ((weaponcargo (_containers select 0)) select 0)];};