["ZSN_Surrenderdistance",	"SLIDER",	["Surrender distance","AI will start surrendering when enemies are closer than this"],				["ZluskeN Hors de Combat","Basic Settings"],[0,1000,100,0],	nil,{params ["_value"]; ZSN_Surrenderdistance = _value;},true] call CBA_fnc_addSetting;
["ZSN_Surrendercount",		"SLIDER",	["Surrender count","AI will surrender when they are fewer than this"],								["ZluskeN Hors de Combat","Basic Settings"],[0,12,2,0],		nil,{params ["_value"]; ZSN_Surrendercount = _value;},true] call CBA_fnc_addSetting;
//["ZSN_WeaponsDrop",			"LIST",		["Units Drop Weapons","Sets whether units will drop their held weapon when they go unconscious"],	["ZluskeN Hors de Combat","Basic Settings"],[["true","AI","false"],["Yes","Only AI","No"],2],nil,{params ["_value"]; ZSN_WeaponsDrop = _value;},true] call CBA_fnc_addSetting;
["ZSN_CreateBox_AI",		"CHECKBOX",	["Spawn crate with gear when handcuffed","A crate is created with the captured units' gear"],		["ZluskeN Hors de Combat","Basic Settings"],False,			nil,{params ["_value"]; ZSN_CreateBox = _value;},true] call CBA_fnc_addSetting;

["ZSN_UnconsciousAction",	"CHECKBOX",	["Unconscious/Captured System","When a player has been unconscious or handcuffed for the time defined below, they will respawned, their body replaced by an AI unit"],["ZluskeN Hors de Combat","Respawn Settings"],False,nil,{params ["_value"]; ZSN_UnconsciousAction = _value;},false] call CBA_fnc_addSetting;
["ZSN_UnconsciousTimer",	"SLIDER",	["Unconscious/Captured Timeout","Time spent Unconscious or handcuffed before above Action happens"],["ZluskeN Hors de Combat","Respawn Settings"],[5,600,300,0],	nil,{params ["_value"]; ZSN_UnconsciousTimer = _value;},true] call CBA_fnc_addSetting;
["ZSN_CreateBox",			"CHECKBOX",	["Spawn crate with gear when respawned","A crate is created with the respawned players' gear"],		["ZluskeN Hors de Combat","Respawn Settings"],False,			nil,{params ["_value"]; ZSN_CreateBox = _value;},true] call CBA_fnc_addSetting;
["ZSN_IncludeLinked",		"CHECKBOX",	["^Include AssignedItems","(Map, GPS, Radio, Compass, Watch and NVGs)"],							["ZluskeN Hors de Combat","Respawn Settings"],False,			nil,{params ["_value"]; ZSN_IncludeLinked = _value;},true] call CBA_fnc_addSetting;
["ZSN_RedeemLiving",		"SLIDER",	["Redeem living units","Living units can be returned to flagpole for extra respawn tickets (TUN Respawn)"],["ZluskeN Hors de Combat","Respawn Settings"],[0,12,1,0],nil,{params ["_value"]; ZSN_RedeemLiving = _value;},true] call CBA_fnc_addSetting;
["ZSN_RequireStabile",		"CHECKBOX",	["Redeem only stabile units","Living units can only be redeemed if they are in stabile condition"],	["ZluskeN Hors de Combat","Respawn Settings"],False,			nil,{params ["_value"]; ZSN_Requirestabile = _value;},true] call CBA_fnc_addSetting;
//["ZSN_SpawnStretcher",		"CHECKBOX",	["Stretcher for Casualties","A stretcher is spawned for wounded units (Vurtual Seat)"],				["ZluskeN Hors de Combat","Respawn Settings"],True,			nil,{params ["_value"]; ZSN_SpawnStretcher = _value;},false] call CBA_fnc_addSetting;
["ZSN_BodyBags",			"CHECKBOX",	["Put dead units in bodybags","When players die, their body is replaced by a bodybag"],				["ZluskeN Hors de Combat","Respawn Settings"],False,			nil,{params ["_value"]; ZSN_BodyBags = _value;},true] call CBA_fnc_addSetting;
["ZSN_RedeemDead",			"SLIDER",	["Redeem dead units","Dead units (in Bodybags) can be returned to flagpole for extra respawn tickets (TUN Respawn)"],["ZluskeN Hors de Combat","Respawn Settings"],[0,12,0,0],nil,{params ["_value"]; ZSN_RedeemDead = _value;},true] call CBA_fnc_addSetting;
